

export const translations = {
  en: {
    sidebar: {
       chat: "Chat & Reason",
       live: "Live Voice",
       transcribe: "Transcribe",
       codegen: "Codegen",
       mergeSimulator: "Merge Simulator", // NEW
       menuSettings: "Menu Settings", 
       dark: "Dark Mode",
       light: "Light Mode",
       proTitle: "Pro Features",
       proDesc: "Experience the power of Gemini 3.0 Pro for complex reasoning and Native Audio for real-time talk."
    },
    settings: { 
       title: "Settings",
       subtitle: "Configure your application preferences",
       appearance: "Appearance",
       language: "Language",
       system: "System",
       reset: "Reset All Settings",
       about: "About",
       version: "Version 1.0.0 (Beta)",
       developer: "Powered by Google Gemini",
       voice: "Default Voice"
    },
    chat: {
       title: "Gemini Pro Chat",
       subtitle: "Powered by Gemini 3.0 Pro",
       thinkingOn: "Thinking Mode On",
       thinkingOff: "Thinking Mode Off",
       thinkingActive: "Thinking mode active: Responses may take longer but will be more thorough.",
       thinkingLoading: "Thinking deeply...",
       placeholder: "Type your message here (Thai or English)...",
       welcome: "Hello! I am Gemini. I can help you with complex tasks, coding, and reasoning in Thai or English.",
       error: "Sorry, I encountered an error processing your request.",
       pdfName: "PDF Document"
    },
    live: {
       listening: "Listening...",
       start: "Start Conversation",
       end: "End Call",
       initial: "Start a real-time voice conversation with Gemini. Speak naturally in Thai or English.",
       error: "Connection error. Please try again.",
       footer: "Gemini 2.5 Live Audio (Preview)",
       voiceLabel: "Voice",
       voices: {
         Puck: "Puck",
         Charon: "Charon",
         Kore: "Kore",
         Fenrir: "Fenrir",
         Zephyr: "Zephyr",
       }
    },
    transcribe: {
       title: "Audio Transcription",
       desc: "Upload an audio file or stream directly to transcribe speech to text using Gemini.",
       uploadLabel: "Upload Audio File",
       uploadDesc: "MP3, WAV, AAC, etc.",
       recordBtn: "Start Streaming",
       recordingBtn: "Streaming... Tap to stop",
       transcribeBtn: "Transcribe File",
       transcribingBtn: "Transcribing...",
       result: "Transcription Result",
       error: "Failed to transcribe audio. Please try again.",
       micError: "Cannot access microphone.",
       copy: "Copy",
       copied: "Copied!"
    },
    codegen: {
      title: "Dual-Core Code Generation",
      subtitle: "Gemini (Drafting) + Claude (Vetting)",
      welcome: "Hello! I'm your AI-powered codegen agent. I draft code with Gemini and vet it with Claude for safety and compliance. What code do you need?",
      placeholder: "Describe the code you need (e.g., 'Python function to calculate Fibonacci sequence')...",
      phaseDrafting: "Drafting code with Gemini...",
      phaseVetting: "Vetting with Claude for security & compliance...",
      phaseBlocked: "Code generation blocked!",
      phaseFinalized: "Code generated and vetted!",
      auditReport: "Security Audit Report",
      flowId: "Flow ID",
      feedback: "Feedback",
      patimokkhaStatus: "Patimokkha Status",
      healthy: "Healthy",
      minorWarnings: "Minor Warnings",
      critical: "Critical",
      notAvailable: "N/A",
      score: "Score",
      error: "An error occurred during code generation or vetting.",
      library: "Library",
      save: "Save",
      saved: "Saved",
      delete: "Delete",
      copy: "Copy",
      copied: "Copied",
      noSavedSnippets: "No saved code snippets yet.",
      savedSnippets: "Saved Code Snippets",
      clearAll: "Clear All",
      confirmClearAll: "Are you sure you want to delete all saved snippets? This action cannot be undone.",
    },
    mergeSimulator: { // NEW
      title: "Merge Strategy Simulator",
      subtitle: "Explore Flask API & JWT with Interactive Merge Logic",
      description: "This interface simulates a Flask API for managing Git merge requests. It features JWT-based authentication and enforces merge strategies based on protected branches.",
      authSection: "Authentication",
      userId: "User ID",
      generateToken: "Get Token",
      generatedToken: "Generated Token",
      tokenPlaceholder: "Enter a user ID (e.g., 'admin', 'dev')",
      tokenError: "Token generation failed.",
      tokenCopied: "Token Copied!",
      secretKey: "SECRET_KEY for JWT",
      mergeSection: "Merge Request Simulation",
      fromBranch: "From Branch",
      toBranch: "To Branch",
      strategy: "Strategy",
      sendRequest: "Send Merge Request",
      response: "API Response",
      responsePlaceholder: "API responses will appear here...",
      mergeSuccess: "Merge simulation successful!",
      mergeFailed: "Merge simulation failed.",
      copyToken: "Copy Token",
      copyCode: "Copy Code",
      copied: "Copied!",
      codeExplanation: "Flask Backend Code",
      codeExplanationDesc: "This Python code defines the backend logic for JWT generation and merge request handling.",
    },
    // NEW: API Key translations
    apiKey: {
      selectKey: "Please select an API Key to enable this feature.",
      selectKeyButton: "Select API Key",
      billingLink: "ai.google.dev/gemini-api/docs/billing", 
      billingLinkText: "Billing Documentation",
      billingMessage: "You must select an API key from a paid GCP project.",
      reselectKey: "API Key failed to authenticate or was not found. Please re-select your API Key.",
      keyNotFound: "API Key not found in environment. Please select one.",
      apiInitFailed: "Failed to initialize Gemini API. Ensure API Key is valid and library version is correct."
    }
  },
  th: {
    sidebar: {
       chat: "แชทและเหตุผล",
       live: "สนทนาสด",
       transcribe: "ถอดความเสียง",
       codegen: "สร้างโค้ด",
       mergeSimulator: "จำลองการผสาน", // NEW
       menuSettings: "การตั้งค่าเมนู", 
       dark: "โหมดมืด",
       light: "โหมดสว่าง",
       proTitle: "ฟีเจอร์โปร",
       proDesc: "สัมผัสพลังของ Gemini 3.0 Pro สำหรับการให้เหตุผลที่ซับซ้อนและ Native Audio เพื่อการสนทนาแบบเรียลไทม์"
    },
    settings: { 
       title: "การตั้งค่า",
       subtitle: "กำหนดค่าแอปพลิเคชัน",
       appearance: "รูปลักษณ์",
       language: "ภาษา",
       system: "ระบบ",
       reset: "รีเซ็ตการตั้งค่าทั้งหมด",
       about: "เกี่ยวกับ",
       version: "เวอร์ชัน 1.0.0 (เบต้า)",
       developer: "ขับเคลื่อนโดย Google Gemini",
       voice: "เสียงเริ่มต้น"
    },
    chat: {
       title: "แชท Gemini Pro",
       subtitle: "ขับเคลื่อนโดย Gemini 3.0 Pro",
       thinkingOn: "โหมดคิดวิเคราะห์: เปิด",
       thinkingOff: "โหมดคิดวิเคราะห์: ปิด",
       thinkingActive: "โหมดคิดวิเคราะห์ทำงานอยู่: การตอบกลับอาจใช้เวลานานขึ้นแต่จะละเอียดรอบคอบกว่า",
       thinkingLoading: "กำลังคิดวิเคราะห์อย่างลึกซึ้ง...",
       placeholder: "พิมพ์ข้อความของคุณที่นี่ (ไทย หรือ อังกฤษ)...",
       welcome: "สวัสดี! ฉันคือ Gemini ฉันสามารถช่วยคุณในงานที่ซับซ้อน การเขียนโค้ด และการให้เหตุผล ทั้งในภาษาไทยและภาษาอังกฤษ",
       error: "ขออภัย เกิดข้อผิดพลาดในการประมวลผลคำขอของคุณ",
       pdfName: "เอกสาร PDF"
    },
    live: {
       listening: "กำลังฟัง...",
       start: "เริ่มการสนทนา",
       end: "วางสาย",
       initial: "เริ่มการสนทนาด้วยเสียงแบบเรียลไทม์กับ Gemini พูดคุยอย่างเป็นธรรมชาติได้ทั้งภาษาไทยและอังกฤษ",
       error: "เกิดข้อผิดพลาดในการเชื่อมต่อ โปรดลองอีกครั้ง",
       footer: "Gemini 2.5 Live Audio (ตัวอย่าง)",
       voiceLabel: "เสียง",
       voices: {
         Puck: "พัค",
         Charon: "แชรอน",
         Kore: "โคเร",
         Fenrir: "เฟนริร์",
         Zephyr: "เซเฟอร์",
       }
    },
    transcribe: {
       title: "ถอดความเสียง",
       desc: "อัปโหลดไฟล์เสียงหรือสตรีมสดเพื่อถอดความพูดเป็นข้อความโดยใช้ Gemini",
       uploadLabel: "อัปโหลดไฟล์เสียง",
       uploadDesc: "MP3, WAV, AAC, ฯลฯ",
       recordBtn: "เริ่มสตรีมมิ่ง",
       recordingBtn: "กำลังสตรีม... แตะเพื่อหยุด",
       transcribeBtn: "ถอดความไฟล์",
       transcribingBtn: "กำลังถอดความ...",
       result: "ผลลัพธ์การถอดความ",
       error: "ไม่สามารถถอดความเสียงได้ โปรดลองอีกครั้ง",
       micError: "ไม่สามารถเข้าถึงไมโครโฟนได้",
       copy: "คัดลอก",
       copied: "คัดลอกแล้ว!"
    },
    codegen: {
      title: "การสร้างโค้ดแบบ Dual-Core",
      subtitle: "Gemini (ร่างโค้ด) + Claude (ตรวจสอบ)",
      welcome: "สวัสดี! ฉันคือเอเจนต์สร้างโค้ดด้วย AI ฉันจะร่างโค้ดด้วย Gemini และตรวจสอบด้วย Claude เพื่อความปลอดภัยและการปฏิบัติตามข้อกำหนด คุณต้องการโค้ดแบบไหน?",
      placeholder: "อธิบายโค้ดที่คุณต้องการ (เช่น 'ฟังก์ชัน Python สำหรับคำนวณลำดับ Fibonacci')...",
      phaseDrafting: "กำลังร่างโค้ดด้วย Gemini...",
      phaseVetting: "กำลังตรวจสอบความปลอดภัยและข้อกำหนดด้วย Claude...",
      phaseBlocked: "การสร้างโค้ดถูกบล็อก!",
      phaseFinalized: "สร้างและตรวจสอบโค้ดเรียบร้อยแล้ว!",
      auditReport: "รายงานการตรวจสอบความปลอดภัย",
      flowId: "ID กระบวนการ",
      feedback: "ข้อเสนอแนะ",
      patimokkhaStatus: "สถานะปาฏิโมกข์",
      healthy: "ปลอดภัย",
      minorWarnings: "มีคำเตือนเล็กน้อย",
      critical: "วิกฤต",
      notAvailable: "ไม่มีข้อมูล",
      score: "คะแนน",
      error: "เกิดข้อผิดพลาดระหว่างการสร้างหรือตรวจสอบโค้ด",
      library: "ไลบรารี",
      save: "บันทึก",
      saved: "บันทึกแล้ว",
      delete: "ลบ",
      copy: "คัดลอก",
      copied: "คัดลอกแล้ว",
      noSavedSnippets: "ยังไม่มีโค้ดที่บันทึกไว้",
      savedSnippets: "โค้ดที่บันทึกไว้",
      clearAll: "ล้างทั้งหมด",
      confirmClearAll: "คุณแน่ใจหรือไม่ว่าต้องการลบโค้ดที่บันทึกไว้ทั้งหมด? การดำเนินการนี้ไม่สามารถย้อนกลับได้",
    },
    mergeSimulator: { // NEW
      title: "เครื่องจำลองกลยุทธ์การผสาน",
      subtitle: "สำรวจ Flask API & JWT ด้วยตรรกะการผสานแบบโต้ตอบ",
      description: "อินเทอร์เฟซนี้จำลอง Flask API สำหรับการจัดการคำขอผสาน Git โดยมีการรับรองความถูกต้องด้วย JWT และบังคับใช้กลยุทธ์การผสานตามสาขาที่ได้รับการป้องกัน",
      authSection: "การรับรองความถูกต้อง",
      userId: "รหัสผู้ใช้",
      generateToken: "สร้างโทเค็น",
      generatedToken: "โทเค็นที่สร้าง",
      tokenPlaceholder: "ป้อนรหัสผู้ใช้ (เช่น 'admin', 'dev')",
      tokenError: "การสร้างโทเค็นล้มเหลว",
      tokenCopied: "คัดลอกโทเค็นแล้ว!",
      secretKey: "SECRET_KEY สำหรับ JWT",
      mergeSection: "การจำลองคำขอผสาน",
      fromBranch: "จากสาขา",
      toBranch: "ถึงสาขา",
      strategy: "กลยุทธ์",
      sendRequest: "ส่งคำขอผสาน",
      response: "การตอบกลับ API",
      responsePlaceholder: "การตอบกลับ API จะปรากฏที่นี่...",
      mergeSuccess: "จำลองการผสานสำเร็จ!",
      mergeFailed: "จำลองการผสานล้มเหลว",
      copyToken: "คัดลอกโทเค็น",
      copyCode: "คัดลอกโค้ด",
      copied: "คัดลอกแล้ว!",
      codeExplanation: "โค้ดแบ็กเอนด์ Flask",
      codeExplanationDesc: "โค้ด Python นี้กำหนดตรรกะแบ็กเอนด์สำหรับการสร้าง JWT และการจัดการคำขอผสาน",
    },
    // NEW: API Key translations
    apiKey: {
      selectKey: "โปรดเลือก API Key เพื่อเปิดใช้งานคุณสมบัตินี้",
      selectKeyButton: "เลือก API Key",
      billingLink: "ai.google.dev/gemini-api/docs/billing", 
      billingLinkText: "เอกสารประกอบการเรียกเก็บเงิน",
      billingMessage: "คุณต้องเลือก API Key จากโปรเจกต์ GCP ที่มีการเรียกเก็บเงิน",
      reselectKey: "API Key ไม่สามารถตรวจสอบสิทธิ์ได้หรือหาไม่พบ โปรดเลือก API Key ใหม่อีกครั้ง",
      keyNotFound: "ไม่พบ API Key ในสภาพแวดล้อม โปรดเลือก API Key",
      apiInitFailed: "ไม่สามารถเริ่มต้น Gemini API ได้ โปรดตรวจสอบว่า API Key ถูกต้องและเวอร์ชันไลบรารีถูกต้อง"
    }
  }
};